import React from 'react';
import {Container} from '../Views/Container';

export const TableBasquet = () => {
  return (
    <>
      <Container
        width={'100%'}
        height={'80%'}
        bg="transparent"
        position="absolute"
        right={0}
        btw={1}
        btc={'black'}
        bbw={1}
        bbc={'black'}
      />
      <Container
        width={'20%'}
        height={'70%'}
        bg="transparent"
        position="absolute"
        right={0}
        btw={1}
        btc={'black'}
        bbw={1}
        bbc={'black'}
      />
      <Container
        width={'69%'}
        height={'70%'}
        bg="transparent"
        position="absolute"
        right={'20%'}
        btw={1}
        btc={'black'}
        bbc={'black'}
        bbw={1}
        bblr={1850}
        btlr={1850}
        blc={'black'}
        blw={1}
      />
      <Container
        width={'53%'}
        height={'22%'}
        bg="transparent"
        position="absolute"
        right={0}
        btw={1}
        blc={'black'}
        blw={1}
        btc={'black'}
        bbc={'black'}
        bbw={1}
      />
      <Container
        width={'22%'}
        height={'22%'}
        bg="transparent"
        position="absolute"
        right={'53%'}
        btw={1}
        btc={'black'}
        bbc={'black'}
        bbw={1}
        bblr={1850}
        btlr={1850}
        blc={'black'}
        blw={1}
      />
      <Container
        width={'17%'}
        height={'17%'}
        bg="transparent"
        position="absolute"
        right={'13%'}
        btw={1}
        btc={'black'}
        bbc={'black'}
        bbw={1}
        bblr={1850}
        btlr={1850}
        blc={'black'}
        blw={1}
      />
      <Container
        width={'7%'}
        height={'4%'}
        bg="transparent"
        position="absolute"
        right={'7%'}
        bc={'black'}
        bw={1}
        br={100}
      />
    </>
  );
};
